---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(randomForest)
library(Boruta)
library(zoo)
library(reshape)
library(ggplot2)
```

#options("scipen"=100, "digits"=4)
```{r}
wdi.data <- read.csv("E:/datasets/WDI_Data.csv",header = T, stringsAsFactors = F, check.names = T )

str(wdi.data)

wdi.data <- dplyr::rename_at(wdi.data, vars(contains("Series.Name")), function(x) x="Series.Name")
wdi.data <- dplyr::rename_at(wdi.data, vars(contains("YR")), function(x) str_extract_all(x, pattern = "YR[0-9]+", simplify = T))

#Take off commas from first column

wdi.data$Series.Name <- gsub(",","", wdi.data$Series.Name)
```

```{r}
str(wdi.data)
dim(wdi.data)

```

#out of 22 columns first four are character class, rest all are numeric
```{r}
for(i in 5:22) {
  wdi.data[[i]] <- as.numeric(wdi.data[[i]])
}

str(wdi.data)

```
Remove 22nd column of 2017 as it has no data
```{r}
wdi.data <- wdi.data[,-22]

ind_pak <- wdi.data %>% 
  filter(wdi.data$Country.Name == "India" | wdi.data$Country.Name == "Pakistan")%>%
  format(scientific =F, digits = 2)
  

head(ind_pak)
colnames(ind_pak)
```

lets melt our data for plotting purpose
```{r,fig.width= 10, fig.height=40}
ind_pak_melt <- melt(ind_pak, id.vars =c("Series.Name", "Series.Code","Country.Name", "Country.Code"),variable_name = "Year")

str(ind_pak_melt)

ind_pak_melt$Year <- as.numeric(gsub("YR","",ind_pak_melt$Year))
ind_pak_melt$value <- as.numeric(ind_pak_melt$value)
ind_pak_melt$Series.Name <- as.character(ind_pak_melt$Series.Name)
ind_pak_melt$Country.Name <- as.character(ind_pak_melt$Country.Name)
ind_pak_melt$Series.Code <- as.character(ind_pak_melt$Series.Code)
ind_pak_melt$Country.Code <- as.character(ind_pak_melt$Country.Code)
```

```{r fig.width= 16, fig.height= 28}

ggplot(ind_pak_melt, aes(x=Year, y=value,fill=ind_pak_melt$Country.Name))+
  facet_wrap("Series.Name", scales = "free", ncol = 3)+
  geom_bar(stat="sum")
```

```{r fig.width= 16, fig.height= 28}
ggplot(ind_pak_melt, aes(x=Year, y=value,fill=ind_pak_melt$Country.Name))+
  facet_wrap("Series.Name", scales = "free", ncol = 3)+
  geom_bar(stat="sum", position = "fill") #Fills entire bar to showcase ratio

```
```{r fig.width= 16, fig.height= 40, }
p1 <- ggplot(ind_pak_melt, aes(x=Year, y=value, fill=Country.Name))+
  facet_wrap("Series.Name", scales = "free", ncol = 2)+
  geom_bar(stat="sum", position = "dodge") #Dodge plots bars aslongside
 

ggsave(filename = "D:/Documents/Ind_Pak_Comparison.pdf", plot = p1, dpi = 300, height = 40, width = 13)


```

```{R}


````


